### ISSUE TITLE
FxCop & StyleCop support?

### ISSUE THREAD

**Issue by doogie2301** [jenkinsci/violation-comments-to-stash-plugin#19]
Maybe I missed something, was the support for these dropped?

**Comment by tomasbjerre** [comment]
Yes. Do you have example report files?

**Comment by tomasbjerre** [comment]
I'm adding support for FxCop. But StyleCop was a bit harder, cannot figure out the filename from the reportfile.

**Comment by tomasbjerre** [comment]
Fxcop is released now.

**Comment by doogie2301** [comment]
Wow that was fast, thanks!  Here's an example of a StyleCop violations file,  The filename should be in the "Source" attribute.

[StyleCopViolations.zip](https://github.com/jenkinsci/violation-comments-to-stash-plugin/files/506623/StyleCopViolations.zip)

**Comment by doogie2301** [comment]
Also just trying the FxCop functionality, I got this error:

Oct 03, 2016 12:21:10 PM SEVERE se.bjurr.violations.lib.reports.Reporter findViolations
Error when parsing E:\Jenkins\jobs\Test Project Pull Requests\workspace\Test Solution 1\GenericsSample\bin\Debug\GenericsSample.exe.CodeAnalysisLog.xml as FXCOP
java.lang.RuntimeException: "Path" not found in:
<?xml version="1.0" encoding="UTF-8"?><Issue Certainty="95" Level="Warning">Because assembly 'GenericsSample.exe' contains a ResX-based resource file, mark it with the NeutralResourcesLanguage attribute, specifying the language of the resources within the assembly. This could improve lookup performance the first time a resource is retrieved.</Issue>
	at se.bjurr.violations.lib.parsers.ViolationParserUtils.getAttribute(ViolationParserUtils.java:75)
	at se.bjurr.violations.lib.parsers.FxCopParser.parseFile(FxCopParser.java:52)
	at se.bjurr.violations.lib.reports.Reporter.findViolations(Reporter.java:58)
	at se.bjurr.violations.lib.ViolationsReporterApi.violations(ViolationsReporterApi.java:53)
	at org.jenkinsci.plugins.jvctb.perform.JvctbPerformer.doPerform(JvctbPerformer.java:66)
	at org.jenkinsci.plugins.jvctb.perform.JvctbPerformer$1.invoke(JvctbPerformer.java:124)
	at org.jenkinsci.plugins.jvctb.perform.JvctbPerformer$1.invoke(JvctbPerformer.java:111)
	at hudson.FilePath.act(FilePath.java:990)
	at hudson.FilePath.act(FilePath.java:968)
	at org.jenkinsci.plugins.jvctb.perform.JvctbPerformer.jvctsPerform(JvctbPerformer.java:111)
	at org.jenkinsci.plugins.jvctb.ViolationsToBitbucketServerRecorder.perform(ViolationsToBitbucketServerRecorder.java:61)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
	at hudson.model.Run.execute(Run.java:1763)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)

I guess issues reported at the project level won't have a "Path" attribute.  I attached the xml file for your testing.
[GenericsSample.exe.CodeAnalysisLog.zip](https://github.com/jenkinsci/violation-comments-to-stash-plugin/files/506705/GenericsSample.exe.CodeAnalysisLog.zip)

**Comment by tomasbjerre** [comment]
Ok nice! I added it to 1.27 now. Should be available in Jenkins Update Center within a few hours.

**Comment by doogie2301** [comment]
I'm sorry, I may have given you an older format for StyleCop, let me do some research and I'll get back to you.

**Comment by doogie2301** [comment]
Nope, it was correct, I think we're good here.
