### ISSUE TITLE
Re-using credentials from System config causes java.lang.NullPointerException: username not set!

### ISSUE THREAD

**Issue by tuukkamustonen** [jenkinsci/violation-comments-to-stash-plugin#22]
In `Manage Jenkins > Configure System`:

![image](https://cloud.githubusercontent.com/assets/94327/19683826/aec178c8-9abc-11e6-9e69-8b824a36e652.png)

In job config:

![image](https://cloud.githubusercontent.com/assets/94327/19683849/cda5fe3a-9abc-11e6-9017-950f886e08cf.png)

I haven't check either username/password combination, because I want to re-use credentials defined in system config.

This causes following trace:

```
---
--- Jenkins Violation Comments to Bitbucket Server ---
---
bitbucketServerUrl: https://mystash.gtn
projectKey: COSMOS
repoSlug: cosmos
pullRequestId: 184
usernamePasswordCredentialsId: true
username: false
password: false
createSingleFileComments: false
createCommentWithAllSingleFileComments: false
ANDROIDLINT with pattern 
CHECKSTYLE with pattern 
CPPCHECK with pattern 
CPPLINT with pattern 
CSSLINT with pattern 
FINDBUGS with pattern 
FLAKE8 with pattern 
FXCOP with pattern 
JSHINT with pattern 
LINT with pattern 
PERLCRITIC with pattern 
PITEST with pattern 
PMD with pattern 
PYLINT with pattern .*/pylint\.out
RESHARPER with pattern 
STYLECOP with pattern 
XMLLINT with pattern 
Will comment 184
Workspace: /home/jenkins/workspace/COSMOS-musttutest
Found 0 violations from ViolationConfig [reporter=PYLINT, pattern=.*/pylint\.out].
java.lang.NullPointerException: username not set!
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:204)
	at org.jenkinsci.plugins.jvctb.perform.JvctbPerformer.doPerform(JvctbPerformer.java:74)
	at org.jenkinsci.plugins.jvctb.perform.JvctbPerformer$1.invoke(JvctbPerformer.java:155)
	at org.jenkinsci.plugins.jvctb.perform.JvctbPerformer$1.invoke(JvctbPerformer.java:142)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2772)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:332)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to flexible-docker-02(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
	at hudson.remoting.Channel.call(Channel.java:781)
	at hudson.FilePath.act(FilePath.java:1007)
	at hudson.FilePath.act(FilePath.java:996)
	at org.jenkinsci.plugins.jvctb.perform.JvctbPerformer.jvctsPerform(JvctbPerformer.java:142)
	at org.jenkinsci.plugins.jvctb.ViolationsToBitbucketServerRecorder.perform(ViolationsToBitbucketServerRecorder.java:61)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1766)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
```

What's interesting is that this doesn't actually fail the build, it continues:

```
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Finished: SUCCESS
```

Adding credentials in job config resolves the problem.

Running 1.30 version. Not sure, but I think it worked in 1.27.

**Comment by tuukkamustonen** [comment]
Hmm, do I actually have to select `User username / password credentials` but select `- None -` from the dropdown in job config? That seems to work.

**Comment by tomasbjerre** [comment]
Yes thats how its implemented. Perhaps it should just default to whatever global config is available.

**Comment by tuukkamustonen** [comment]
I don't know, I guess it's logical because you can then specify both credentials and username+password combination in system config, and then choose which one to pick in job config.

Although... that doesn't sound a likely use case. But it's a feature nevertheless!

Jenkins should really implement 3 states for checkboxes: enabled, disabled, undefined (=use default)...

Anyway, I think current behavior is just fine and there's even documentation about it:

![image](https://cloud.githubusercontent.com/assets/94327/19688248/9a1b1dce-9ad1-11e6-82c0-0ac11f9187f8.png)
