### ISSUE TITLE
Comments publish to PR fails to incorrect Stash API invocation

### ISSUE THREAD

**Issue by tuukkamustonen** [jenkinsci/violation-comments-to-stash-plugin#23]
With 1.30, publishing comments to PR fails to:

```
Found 59 violations from ViolationConfig [reporter=PYLINT, pattern=.*/pylint\.out$].
Will comment PR COSMOS/cosmos/185 on https://mystash.gtn
java.lang.RuntimeException: Error calling:
https://mystash.gtn/rest/api/1.0/projects/COSMOS/repos/cosmos/pull-requests/185/comments
POST
{...SNIP CONTENTS...}
	at se.bjurr.violations.comments.bitbucketserver.lib.client.BitbucketServerInvoker.invokeUrl(BitbucketServerInvoker.java:56)
	at se.bjurr.violations.comments.bitbucketserver.lib.client.BitbucketServerClient.pullRequestComment(BitbucketServerClient.java:46)
	at se.bjurr.violations.comments.bitbucketserver.lib.BitbucketServerCommentsProvider.createCommentWithAllSingleFileComments(BitbucketServerCommentsProvider.java:43)
	at se.bjurr.violations.comments.lib.CommentsCreator.createCommentWithAllSingleFileComments(CommentsCreator.java:66)
	at se.bjurr.violations.comments.lib.CommentsCreator.createComments(CommentsCreator.java:50)
	at se.bjurr.violations.comments.lib.CommentsCreator.createComments(CommentsCreator.java:25)
	at se.bjurr.violations.comments.bitbucketserver.lib.ViolationCommentsToBitbucketServerApi.toPullRequest(ViolationCommentsToBitbucketServerApi.java:80)
	at org.jenkinsci.plugins.jvctb.perform.JvctbPerformer.doPerform(JvctbPerformer.java:91)
	at org.jenkinsci.plugins.jvctb.perform.JvctbPerformer$1.invoke(JvctbPerformer.java:155)
	at org.jenkinsci.plugins.jvctb.perform.JvctbPerformer$1.invoke(JvctbPerformer.java:142)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2772)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:332)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://mystash.gtn/rest/api/1.0/projects/COSMOS/repos/cosmos/pull-requests/185/comments
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at se.bjurr.violations.comments.bitbucketserver.lib.client.BitbucketServerInvoker.invokeUrl(BitbucketServerInvoker.java:47)
	... 18 more
```

Going to `https://mystash.gtn/rest/api/1.0/projects/COSMOS/repos/cosmos/pull-requests/185/comments` in browser (with credentials) gives 400 with body:

```
{"errors":[{"context":null,"message":"The path query parameter is required when retrieving comments.","exceptionName":null}]}
```

It seems like `path` query parameter is indeed required, see: https://jira.atlassian.com/browse/BSERV-7643 (that was closed as wontfix). That ticket leads to https://answers.atlassian.com/questions/21634693/answers/21634860. To retrieve also generic comments, the tickets suggest to use activation API instead:

```
/rest/api/1.0/projects/{projectKey}/repos/{repositorySlug}/pull-requests/{pullRequestId}/activities
```

Or, if general comments are not required, appending `?path=...` to query seems to indeed pass the query (but it seems like you have to throw query per file..?).

Running Bitbucket Server 4.9.1.

**Comment by tuukkamustonen** [comment]
Uh, it's actually trying to do POST not GET... I'll try to reproduce the request locally...

**Comment by tuukkamustonen** [comment]
See: https://github.com/jenkinsci/violation-comments-to-stash-plugin/issues/24
