### ISSUE TITLE
NPE since v1.76

### ISSUE THREAD

**Issue by jansohn** [jenkinsci/violation-comments-to-stash-plugin#57]
We're getting a NPE since v1.76 (same with v1.77). We're using the global Bitbucket Base URL (Configure System -> Bitbucket Server Violations Server Defaults) and do not define it explicitly in our Pipeline script.

    Publish results to Bitbucket server...
    [Pipeline] ViolationsToBitbucketServer
    [Pipeline] }
    [Pipeline] // stage
    [Pipeline] }
    [Pipeline] // node
    [Pipeline] End of Pipeline
    [Bitbucket] Notifying pull request build result
    [Bitbucket] Build result notified
    java.lang.NullPointerException
    	at java.net.URL.<init>(URL.java:532)
    Caused: java.net.MalformedURLException
    	at java.net.URL.<init>(URL.java:627)
    	at java.net.URL.<init>(URL.java:490)
    	at java.net.URL.<init>(URL.java:439)
    	at org.jenkinsci.plugins.jvctb.ViolationsToBitbucketServerRecorder.createProxyConfigDetails(ViolationsToBitbucketServerRecorder.java:96)
    	at org.jenkinsci.plugins.jvctb.ViolationsToBitbucketServerRecorder.perform(ViolationsToBitbucketServerRecorder.java:77)
    	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
    	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
    	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:50)
    	at hudson.security.ACL.impersonate(ACL.java:290)
    	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:47)
    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    	at java.lang.Thread.run(Thread.java:748)
    Finished: FAILURE

**Comment by tomasbjerre** [comment]
You are using globally configured Bitbucket Server URL right? Releasing a fix now as 1.78.
