### ISSUE TITLE
NPE after deleting comments

### ISSUE THREAD

**Issue by jansohn** [jenkinsci/violation-comments-to-stash-plugin#64]
We are seeing NPEs when the plugin deletes previous comments on Bitbucket pull requests. 

Plugin version: `1.103`
Jenkins version: `2.164.1`
Bitbucket version: `5.9.0`
Job type: Multibranch Pipeline

Example:
- first build correctly creates 11 comments on Bitbucket PR:
```
Found 11 violations from ViolationConfig [pattern=.*spotbugsXml\.xml$, reporter=Findbugs, parser=FINDBUGS].
```
- second build still finds two violations, deletes 9 old comments but leaves two comments. I'm pretty sure that previous versions recreated the comments so reviewers got new notifications. Additionally for every deleted comment it sends an additional GET request which fails with a NPE.
```
Found 2 violations from ViolationConfig [pattern=.*spotbugsXml\.xml$, reporter=Findbugs, parser=FINDBUGS].
[...]
INFO Asking BitbucketServerCommentsProvider to comment:
INFO GET https://bitbucket.internal.com/rest/api/1.0/projects/PROJECT/repos/repo-id/pull-requests/1/comments/11046 200 
INFO DELETE https://bitbucket.internal.com/rest/api/1.0/projects/PROJECT/repos/repo-id/pull-requests/1/comments/11046?version=0 204 
INFO GET https://bitbucket.internal.com/rest/api/1.0/projects/PROJECT/repos/repo-id/pull-requests/1/comments/11045 200 
INFO DELETE https://bitbucket.internal.com/rest/api/1.0/projects/PROJECT/repos/repo-id/pull-requests/1/comments/11045?version=0 204 
INFO GET https://bitbucket.internal.com/rest/api/1.0/projects/PROJECT/repos/repo-id/pull-requests/1/comments/11048 200 
INFO DELETE https://bitbucket.internal.com/rest/api/1.0/projects/PROJECT/repos/repo-id/pull-requests/1/comments/11048?version=0 204 
INFO GET https://bitbucket.internal.com/rest/api/1.0/projects/PROJECT/repos/repo-id/pull-requests/1/comments/11047 200 
INFO DELETE https://bitbucket.internal.com/rest/api/1.0/projects/PROJECT/repos/repo-id/pull-requests/1/comments/11047?version=0 204 
INFO GET https://bitbucket.internal.com/rest/api/1.0/projects/PROJECT/repos/repo-id/pull-requests/1/comments/11041 200 
INFO DELETE https://bitbucket.internal.com/rest/api/1.0/projects/PROJECT/repos/repo-id/pull-requests/1/comments/11041?version=0 204 
INFO GET https://bitbucket.internal.com/rest/api/1.0/projects/PROJECT/repos/repo-id/pull-requests/1/comments/11040 200 
INFO DELETE https://bitbucket.internal.com/rest/api/1.0/projects/PROJECT/repos/repo-id/pull-requests/1/comments/11040?version=0 204 
INFO GET https://bitbucket.internal.com/rest/api/1.0/projects/PROJECT/repos/repo-id/pull-requests/1/comments/11044 200 
INFO DELETE https://bitbucket.internal.com/rest/api/1.0/projects/PROJECT/repos/repo-id/pull-requests/1/comments/11044?version=0 204 
INFO GET https://bitbucket.internal.com/rest/api/1.0/projects/PROJECT/repos/repo-id/pull-requests/1/comments/11043 200 
INFO DELETE https://bitbucket.internal.com/rest/api/1.0/projects/PROJECT/repos/repo-id/pull-requests/1/comments/11043?version=0 204 
INFO GET https://bitbucket.internal.com/rest/api/1.0/projects/PROJECT/repos/repo-id/pull-requests/1/comments/11042 200 
INFO DELETE https://bitbucket.internal.com/rest/api/1.0/projects/PROJECT/repos/repo-id/pull-requests/1/comments/11042?version=0 204 
INFO GET https://bitbucket.internal.com/rest/api/1.0/projects/PROJECT/repos/repo-id/pull-requests/1/comments/11048 404 
SEVERE java.lang.NullPointerException
	at se.bjurr.violations.comments.bitbucketserver.lib.client.BitbucketServerClient.toBitbucketServerComment(BitbucketServerClient.java:298)
	at se.bjurr.violations.comments.bitbucketserver.lib.client.BitbucketServerClient.pullRequestComment(BitbucketServerClient.java:184)
	at se.bjurr.violations.comments.bitbucketserver.lib.BitbucketServerCommentsProvider.removeComments(BitbucketServerCommentsProvider.java:158)
	at se.bjurr.violations.comments.lib.CommentsCreator.removeOldCommentsThatAreNotStillReported(CommentsCreator.java:152)
	at se.bjurr.violations.comments.lib.CommentsCreator.createSingleFileComments(CommentsCreator.java:114)
	at se.bjurr.violations.comments.lib.CommentsCreator.createComments(CommentsCreator.java:67)
	at se.bjurr.violations.comments.lib.CommentsCreator.createComments(CommentsCreator.java:39)
	at se.bjurr.violations.comments.bitbucketserver.lib.ViolationCommentsToBitbucketServerApi.toPullRequest(ViolationCommentsToBitbucketServerApi.java:191)
	at org.jenkinsci.plugins.jvctb.perform.JvctbPerformer.doPerform(JvctbPerformer.java:163)
	at org.jenkinsci.plugins.jvctb.perform.JvctbPerformer$2.invoke(JvctbPerformer.java:249)
	at org.jenkinsci.plugins.jvctb.perform.JvctbPerformer$2.invoke(JvctbPerformer.java:237)
	at hudson.FilePath.act(FilePath.java:1074)
	at hudson.FilePath.act(FilePath.java:1057)
	at org.jenkinsci.plugins.jvctb.perform.JvctbPerformer.jvctsPerform(JvctbPerformer.java:236)
	at org.jenkinsci.plugins.jvctb.ViolationsToBitbucketServerRecorder.perform(ViolationsToBitbucketServerRecorder.java:73)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

INFO GET https://bitbucket.internal.com/rest/api/1.0/projects/PROJECT/repos/repo-id/pull-requests/1/comments/11047 404 
SEVERE java.lang.NullPointerException
	at se.bjurr.violations.comments.bitbucketserver.lib.client.BitbucketServerClient.toBitbucketServerComment(BitbucketServerClient.java:298)
    [...]

INFO GET https://bitbucket.internal.com/rest/api/1.0/projects/PROJECT/repos/repo-id/pull-requests/1/comments/11046 404 
SEVERE java.lang.NullPointerException
	at se.bjurr.violations.comments.bitbucketserver.lib.client.BitbucketServerClient.toBitbucketServerComment(BitbucketServerClient.java:298)
    [...]

INFO GET https://bitbucket.internal.com/rest/api/1.0/projects/PROJECT/repos/repo-id/pull-requests/1/comments/11045 404 
SEVERE java.lang.NullPointerException
	at se.bjurr.violations.comments.bitbucketserver.lib.client.BitbucketServerClient.toBitbucketServerComment(BitbucketServerClient.java:298)
    [...]

INFO GET https://bitbucket.internal.com/rest/api/1.0/projects/PROJECT/repos/repo-id/pull-requests/1/comments/11044 404 
SEVERE java.lang.NullPointerException
	at se.bjurr.violations.comments.bitbucketserver.lib.client.BitbucketServerClient.toBitbucketServerComment(BitbucketServerClient.java:298)
    [...]

INFO GET https://bitbucket.internal.com/rest/api/1.0/projects/PROJECT/repos/repo-id/pull-requests/1/comments/11043 404 
SEVERE java.lang.NullPointerException
	at se.bjurr.violations.comments.bitbucketserver.lib.client.BitbucketServerClient.toBitbucketServerComment(BitbucketServerClient.java:298)
    [...]

INFO GET https://bitbucket.internal.com/rest/api/1.0/projects/PROJECT/repos/repo-id/pull-requests/1/comments/11042 404 
SEVERE java.lang.NullPointerException
	at se.bjurr.violations.comments.bitbucketserver.lib.client.BitbucketServerClient.toBitbucketServerComment(BitbucketServerClient.java:298)
    [...]

INFO GET https://bitbucket.internal.com/rest/api/1.0/projects/PROJECT/repos/repo-id/pull-requests/1/comments/11041 404 
SEVERE java.lang.NullPointerException
	at se.bjurr.violations.comments.bitbucketserver.lib.client.BitbucketServerClient.toBitbucketServerComment(BitbucketServerClient.java:298)
    [...]

INFO GET https://bitbucket.internal.com/rest/api/1.0/projects/PROJECT/repos/repo-id/pull-requests/1/comments/11040 404 
SEVERE java.lang.NullPointerException
	at se.bjurr.violations.comments.bitbucketserver.lib.client.BitbucketServerClient.toBitbucketServerComment(BitbucketServerClient.java:298)
    [...]
```

**Comment by jansohn** [comment]
Plugin configuration
```
ViolationsToBitbucketServer([
    createCommentWithAllSingleFileComments: false,
    createSingleFileComments: true,
    projectKey: "${projectKey}",
    repoSlug: "${repoSlug}",
    pullRequestId: env.CHANGE_ID,
    keepOldComments: false,
    violationConfigs: [
        [ pattern: '.*checkstyle-result\\.xml$', parser: 'CHECKSTYLE', reporter: 'Checkstyle' ],
        [ pattern: '.*spotbugsXml\\.xml$', parser: 'FINDBUGS', reporter: 'Findbugs' ]
    ]
])
```

**Comment by tomasbjerre** [comment]
Should work now. Or else open issue again!
